In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings("ignore")


In [6]:
bitdf=pd.read_csv("BitcoinPrice (4).csv")

In [7]:
bitdf.head()

Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [8]:
bitdf.tail()

Date         Price
360  2019-08-20 00:00:00  10746.507692
361  2019-08-21 00:00:00  10169.094167
362  2019-08-22 00:00:00  10030.746667
363  2019-08-23 00:00:00  10255.977500
364  2019-08-24 00:00:00  10158.540833

In [9]:
bitdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    365 non-null    object 
 1   Price   365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB


In [10]:
bitdf.drop(['Date'],1,inplace=True)

In [11]:
bitdf.head()

Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

In [12]:
pt_days=30
bitdf['Predicted value']=bitdf[['Price']].shift(-pt_days)

In [14]:
bitdf.head()

Price  Predicted value
0  6719.429231      6639.304167
1  6673.274167      6412.459167
2  6719.266154      6468.631667
3  7000.040000      6535.476667
4  7054.276429      6677.342500

In [15]:
bitdf.tail()

Price  Predicted value
360  10746.507692              NaN
361  10169.094167              NaN
362  10030.746667              NaN
363  10255.977500              NaN
364  10158.540833              NaN

In [16]:
x=np.array(bitdf.drop(['Predicted value'],1))
x=x[:len(bitdf)-pt_days]
           

In [18]:
x.shape

(335, 1)

In [19]:
x

array([[ 6719.42923077],
       [ 6673.27416667],
       [ 6719.26615385],
       [ 7000.04      ],
       [ 7054.27642857],
       [ 6932.6625    ],
       [ 6981.94615385],
       [ 7100.94666667],
       [ 7247.93538462],
       [ 7260.94923077],
       [ 7326.8525    ],
       [ 7113.06923077],
       [ 6433.27166667],
       [ 6444.80416667],
       [ 6366.1075    ],
       [ 6286.42583333],
       [ 6297.87769231],
       [ 6296.32083333],
       [ 6273.1375    ],
       [ 6450.17923077],
       [ 6499.0625    ],
       [ 6518.655     ],
       [ 6480.64416667],
       [ 6400.60083333],
       [ 6296.63166667],
       [ 6335.82666667],
       [ 6418.56266667],
       [ 6669.99083333],
       [ 6709.3125    ],
       [ 6710.445     ],
       [ 6639.30416667],
       [ 6412.45916667],
       [ 6468.63166667],
       [ 6535.47666667],
       [ 6677.3425    ],
       [ 6550.47416667],
       [ 6593.135     ],
       [ 6590.96833333],
       [ 6562.64166667],
       [ 6470.4025    ],


In [20]:
y=np.array(bitdf['Predicted value'])
y=y[:-pt_days]

In [22]:
y.shape

(335,)

In [23]:
y

array([ 6639.30416667,  6412.45916667,  6468.63166667,  6535.47666667,
        6677.3425    ,  6550.47416667,  6593.135     ,  6590.96833333,
        6562.64166667,  6470.4025    ,  6563.62833333,  6568.54916667,
        6581.48666667,  6558.5375    ,  6618.56769231,  6621.71166667,
        6563.00916667,  6248.63583333,  6260.53083333,  6260.64583333,
        6299.39916667,  6452.57166667,  6596.61833333,  6596.27615385,
        6568.04076923,  6487.44416667,  6488.82583333,  6531.60166667,
        6498.48583333,  6481.426     ,  6508.31      ,  6478.0825    ,
        6473.75333333,  6465.9175    ,  6448.22166667,  6382.66833333,
        6309.45285714,  6310.28416667,  6342.28083333,  6387.67416667,
        6363.79583333,  6391.87333333,  6436.965     ,  6445.35416667,
        6538.79      ,  6486.25166667,  6411.28083333,  6399.03333333,
        6378.26833333,  6401.93666667,  6372.06333333,  6176.155     ,
        5615.18      ,  5596.1925    ,  5558.24333333,  5606.04416667,
      

In [24]:
#split the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [25]:
x_train

array([[ 3998.4975    ],
       [ 7896.51083333],
       [ 3458.06666667],
       [ 7152.48416667],
       [ 7765.68833333],
       [ 3832.92166667],
       [ 7941.22166667],
       [ 5302.9575    ],
       [ 3749.56833333],
       [ 9708.43583333],
       [ 4034.13833333],
       [ 6568.54916667],
       [ 7247.93538462],
       [11560.6025    ],
       [11779.45083333],
       [ 3995.32333333],
       [10021.325     ],
       [ 5251.19      ],
       [ 6669.99083333],
       [ 4106.87166667],
       [11577.69538462],
       [ 5031.475     ],
       [ 7848.41583333],
       [ 6538.79      ],
       [ 5851.67076923],
       [ 5558.24333333],
       [ 8163.66333333],
       [ 4011.0925    ],
       [ 6399.03333333],
       [ 6833.35083333],
       [ 3920.45666667],
       [ 3589.26083333],
       [ 9791.0175    ],
       [ 5262.36333333],
       [ 4025.02583333],
       [ 8114.9325    ],
       [ 6444.80416667],
       [ 3833.31083333],
       [ 3827.69083333],
       [ 4026.63583333],


In [26]:
p_days_arr=np.array(bitdf.drop(['Predicted value'],1))[-pt_days:]

In [28]:
print(p_days_arr)

[[ 9774.2575    ]
 [ 9725.4025    ]
 [ 9500.32416667]
 [ 9533.97933333]
 [ 9539.7125    ]
 [ 9873.81166667]
 [10088.8       ]
 [10478.90166667]
 [10790.63      ]
 [10826.275     ]
 [11713.16166667]
 [11759.01916667]
 [11703.73833333]
 [11803.88833333]
 [11816.9125    ]
 [11586.1725    ]
 [11377.80416667]
 [11397.80166667]
 [11144.38916667]
 [10450.81333333]
 [ 9988.9475    ]
 [10230.73333333]
 [10292.38333333]
 [10295.1175    ]
 [10605.82583333]
 [10746.50769231]
 [10169.09416667]
 [10030.74666667]
 [10255.9775    ]
 [10158.54083333]]


In [29]:
from sklearn.ensemble import RandomForestRegressor
Rf=RandomForestRegressor(n_estimators=1000,random_state=1)
Rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=1)

In [30]:
print("Random Forest accuracy:{:.2f}%".format(Rf.score(x_test,y_test)*100))

Random Forest accuracy:86.78%


In [31]:
rf_predict=Rf.predict(x_test)

In [32]:
print(rf_predict)

[ 5207.20465917  6452.97943583  3862.7690366   3837.05862269
  3908.60670417  3745.68893702  6501.07300333  5776.24755083
  5207.20465917  3852.41303417  3707.54719083 10384.20575417
 10142.69553103  5892.32140167  9790.802358    4083.71591917
  7927.01670333  6386.8341175  11234.3604825   4643.14527846
  6377.30386     3700.88909464 10254.25431808 10133.16341577
  3926.94414975  5418.81526917  4552.44942532 10719.22740301
  8249.29487167  3739.60734702  3680.50211205  5701.37034833
  4073.68764699  4538.05137392  4580.6407025   4056.41439167
 10056.9148041   9790.802358    4544.67978917  4087.65916654
  3766.97977904 10553.98885583  6660.06954333  5729.81679686
  4247.4950034  11224.6006775   5893.74579583 10930.50885333
  3710.56474798  4000.12534917 11537.16262167  7432.96380583
  4914.57011038  3852.41303417  7432.96380583  6143.33269583
  5286.873865    6507.20204583  6337.85161667 11335.92921083
 10376.17712583  6331.456045    6883.70945417  5228.63027167
  3672.91579083  5776.41

In [33]:
rf_pred_30=Rf.predict(p_days_arr)

In [34]:
print(rf_pred_30)

[10453.8958975  10332.44715833 10324.84594417 10281.66712333
 10281.66712333 10432.8093725  10213.9008725  10302.26920808
 10067.2828841  10079.1434316  10042.550405   10883.70787467
 10060.72682333 11265.0461875  10326.40622083 11229.432935
 11234.3604825  11234.3604825  11305.43253833 10254.25431808
 10156.9640575  10133.91374955 10131.98748205 10131.98748205
 10593.68235609 10056.9148041  10208.46749686 10155.90209833
 10149.12415288 10212.09402019]


In [37]:
bitdf.head(30)


Price  Predicted value
0   6719.429231      6639.304167
1   6673.274167      6412.459167
2   6719.266154      6468.631667
3   7000.040000      6535.476667
4   7054.276429      6677.342500
5   6932.662500      6550.474167
6   6981.946154      6593.135000
7   7100.946667      6590.968333
8   7247.935385      6562.641667
9   7260.949231      6470.402500
10  7326.852500      6563.628333
11  7113.069231      6568.549167
12  6433.271667      6581.486667
13  6444.804167      6558.537500
14  6366.107500      6618.567692
15  6286.425833      6621.711667
16  6297.877692      6563.009167
17  6296.320833      6248.635833
18  6273.137500      6260.530833
19  6450.179231      6260.645833
20  6499.062500      6299.399167
21  6518.655000      6452.571667
22  6480.644167      6596.618333
23  6400.600833      6596.276154
24  6296.631667      6568.040769
25  6335.826667      6487.444167
26  6418.562667      6488.825833
27  6669.990833      6531.601667
28  6709.312500      6498.485833
29  6710.445000      6481.426000